package edu_bot.additional_class;

public enum Emoji
{

    /**Группы Emoji*/

    /** Смайлы и люди*/
    /**😀 - ухмыляющееся лицо*/ Gringing_Face ("\uD83D\uDE00"),
    /**😁 - ухмыляющееся лицо с подмигивающими глазами*/ Beaming_Face_With_Smiling_Eyes("\uD83D\uDE01"),
    /**😂 - лицо со слезами радости*/ Face_With_Tears_of_Joy("\uD83D\uDE02"),
    /**🤣 - катаюсь по полу от смеха*/ Rolling_on_the_Floor_Laughing("\uD83E\uDD23"),
    /**😃*/ Grinning_Face_With_Big_Eyes("\uD83D\uDE03"),
    /**😄*/ Grinning_Face_With_Smiling_Eyes("\uD83D\uDE04"),
    /**😅*/ Grinning_Face_With_Sweat("\uD83D\uDE05"),
    /**😆*/ Grinning_Squinting_Face("\uD83D\uDE06"),
    /**😉 - подмигивающее лицо*/ Winking_Face("\uD83D\uDE09"),
    /**😊 - улыбающееся лицо с улыбающимися глазами*/ Smiling_Face_With_Smiling_Eyes("\uD83D\uDE0A"),
    /**😋*/ Face_Savoring_Food("\uD83D\uDE0B"),
    /**😎*/ Smiling_Fac_With_Sunglasses("\uD83D\uDE0E"),
    /**😍 - улыбающееся лицо с глазами-сердечками*/ Smiling_Face_With_Heart_Eyes("\uD83D\uDE0D"),
    /**😘*/ Face_Blowing_a_Kiss("\uD83D\uDE18"),
    /**😗*/ Kissing_Face("\uD83D\uDE17"),
    /**😙*/ Kissing_Face_With_Smiling_Eyes("\uD83D\uDE19"),
    /**😚*/ Kissing_Face_With_Closed_Eyes("\uD83D\uDE1A"),
    /**☺*/ Smiling_Face("☺"),
    /**🙂*/ Slightly_Smiling_Face("\uD83D\uDE42"),
    /**🤗*/ Hugging_Face("\uD83E\uDD17"),
    /**🤩*/ Star_Struck("\uD83E\uDD29"),
    /**🤔*/ Thinking_Face("\uD83E\uDD14"),
    /**🤨*/ Face_With_Raised_Eyebrow("\uD83E\uDD28"),
    /**😐*/ Neutral_Face("\uD83D\uDE10"),
    /**😑*/ Expressionless_Face("\uD83D\uDE11"),
    /**😶*/ Face_Without_Mouth("\uD83D\uDE36"),
    /**🙄*/ Face_With_Rolling_Eyes("\uD83D\uDE44"),
    /**😏*/ Smirking_Face("\uD83D\uDE0F"),
    /**😣*/ Persevering_Face("\uD83D\uDE23"),
    /**😥*/ Sad_but_Relieved_Face("\uD83D\uDE25"),
    /**😮*/ Face_With_Open_Mouth("\uD83D\uDE2E"),
    /**🤐*/ Zipper_Mouth_Face("\uD83E\uDD10"),
    /**😯*/ Hushed_Face("\uD83D\uDE2F"),
    /**😪*/ Sleepy_Face("\uD83D\uDE2A"),
    /**😫*/ Tired_Face("\uD83D\uDE2B"),
    /**😴*/ Sleeping_Face("\uD83D\uDE34"),
    /**😌*/ Relieved_Face("\uD83D\uDE0C"),
    /**😛*/ Face_With_Tongue("\uD83D\uDE1B"),
    /**😜*/ Winking_Face_With_Tongue("\uD83D\uDE1C"),
    /**😝*/ Squinting_Face_With_Tongue("\uD83D\uDE1D"),
    /**🤤*/ Drooling_Face("\uD83E\uDD24"),
    /**😒*/ Unamused_Face("\uD83D\uDE12"),
    /**😓*/ Downcast_Face_With_Sweat(""),
    /**😔*/ Pensive_Face("\uD83D\uDE13"),
    /**😕*/ Confused_Face("\uD83D\uDE15"),
    /**🙃*/ Upside_Down_Face("\uD83D\uDE43"),
    /**🤑*/ Money_Mouth_Face("\uD83E\uDD11"),
    /**😲*/ Astonished_Face("\uD83D\uDE32"),
    /**☹*/ Frowning_Face("☹"),
    /**🙁*/ Slightly_Frowning_Face("\uD83D\uDE41"),
    /**😖*/ Confounded_Face("\uD83D\uDE16"),
    /**😞*/ Disappointed_Face("\uD83D\uDE1E"),
    /**😟*/ Worried_Face("\uD83D\uDE1F"),
    /**😤*/ Face_With_Steam_From_Nose("\uD83D\uDE24"),
    /**😢*/ Crying_Face("\uD83D\uDE22"),
    /**😭*/ Loudly_Crying_Face("\uD83D\uDE2D"),
    /**😦*/ Frowning_Face_With_Open_Mouth("\uD83D\uDE26"),
    /**😧*/ Anguished_Face("\uD83D\uDE27"),
    /**😨*/ Fearful_Face("\uD83D\uDE28"),
    /**😩*/ Weary_Face("\uD83D\uDE29"),
    /**🤯*/ Exploding_Head("\uD83E\uDD2F"),
    /**😬*/ Grimacing_Face("\uD83D\uDE2C"),
    /**😰*/ Anxious_Face_With_Sweat("\uD83D\uDE30"),
    /**😱*/ Face_Screaming_in_Fear("\uD83D\uDE31"),
    /**😳*/ Flushed_Face("\uD83D\uDE33"),
    /**🤪*/ Zany_Face("\uD83E\uDD2A"),
    /**😵*/ Dizzy_Face("\uD83D\uDE35"),
    /**😡*/ Pouting_Face("\uD83D\uDE21"),
    /**😠*/ Angry_Face("\uD83D\uDE20"),
    /**🤬*/ Face_With_Symbols_on_Mouth("\uD83E\uDD2C"),
    /**😷*/ Face_With_Medical_Mask("\uD83D\uDE37"),
    /**🤒*/ Face_With_Thermometer("\uD83E\uDD12"),
    /**🤕*/ Face_With_Head_Bandage("\uD83E\uDD15"),
    /**🤢*/ Nauseated_Face("\uD83E\uDD22"),
    /**🤮*/ Face_Vomiting("\uD83E\uDD2E"),
    /**🤧*/ Sneezing_Face("\uD83E\uDD27"),
    /**😇*/ Smiling_Face_With_Halo("\uD83D\uDE07"),
    /**🤠*/ Cowboy_Hat_Face("\uD83E\uDD20"),
    /**🤡*/ Clown_Face("\uD83E\uDD21"),
    /**🤥*/ Lying_Face("\uD83E\uDD25"),
    /**🤫*/ Shushing_Face("\uD83E\uDD2B"),
    /**🤭*/ Face_With_Hand_Over_Mouth("\uD83E\uDD2D"),
    /**🧐*/ Face_With_Monocle("\uD83E\uDDD0"),
    /**🤓*/ Nerd_Face("\uD83E\uDD13"),
    /**😈*/ Smiling_Face_With_Horns("\uD83D\uDE08"),
    /**👿*/ Angry_Face_With_Horns("\uD83D\uDC7F"),
    /**👹*/ Ogre("\uD83D\uDC79"),
    /**👺*/ Goblin("\uD83D\uDC7A"),
    /**💀*/ Skull("\uD83D\uDC80"),
    /**👻*/ Ghost("\uD83D\uDC7B"),
    /**👽*/ Alien("\uD83D\uDC7D"),
    /**🤖*/ Robot_Face("\uD83E\uDD16"),
    /**💩*/ Pile_of_Poo("\uD83D\uDCA9"),
    /**😺*/ Grinning_Cat_Face("\uD83D\uDE3A"),
    /**😸*/ Grinning_Cat_Face_With_Smiling_Eyes("\uD83D\uDE38"),
    /**😹*/ Cat_Face_With_Tears_of_Joy("\uD83D\uDE39"),
    /**😻*/ Smiling_Cat_Face_With_Heart_Eyes("\uD83D\uDE3B"),
    /**😼*/ Cat_Face_With_Wry_Smile("\uD83D\uDE3C"),
    /**😽*/ Kissing_Cat_Face("\uD83D\uDE3D"),
    /**🙀*/ Weary_Cat_Face("\uD83D\uDE40"),
    /**😿*/ Crying_Cat_Face("\uD83D\uDE3F"),
    /**😾*/ Pouting_Cat_Face("\uD83D\uDE3E"),
    /**👶*/ Baby("\uD83D\uDC76"),
    /**👦*/ Boy("\uD83D\uDC66"),
    /**👧*/ Girl("\uD83D\uDC67"),
    /**👨*/ Man("\uD83D\uDC68"),
    /**👩*/ Woman("\uD83D\uDC69"),
    /**👴*/ Old_Man("\uD83D\uDC74"),
    /**👵*/ Old_Woman("\uD83D\uDC75"),
    /**👨‍⚕️*/ Man_Health_Worker("\uD83D\uDC68\u200D⚕️"),
    /**👩‍⚕ ️*/ Woman_Health_Worker("\uD83D\uDC69\u200D⚕️"),
    /**👨‍🎓*/ Man_Student("\uD83D\uDC68\u200D\uD83C\uDF93"),
    /**👩‍🎓*/ Woman_Student("\u200D\uD83C\uDF93"),
    /**👨‍⚖️*/ Man_Judge("\u200D⚖️"),
    /**👩‍⚖️*/ Woman_Judge("\uD83D\uDC69\u200D⚖️"),
    /**👨‍🌾*/ Man_Farmer("\u200D\uD83C\uDF3E"),
    /**👩‍🌾*/ Woman_Farmer("\uD83D\uDC69\u200D\uD83C\uDF3E"),
    /**👨‍🍳*/ Man_Cook("\uD83D\uDC68\u200D\uD83C\uDF73"),
    /**👩‍🍳*/ Woman_Cook("\uD83D\uDC69\u200D\uD83C\uDF73"),
    /**👨‍🔧*/ Man_Mechanic("\uD83D\uDC68\u200D\uD83D\uDD27"),
    /**👩‍🔧*/ Woman_Mechanic("\uD83D\uDC69\u200D\uD83D\uDD27"),
    /**👨‍🏭*/ Man_Factory_Worker("\uD83D\uDC68\u200D\uD83C\uDFED"),
    /**👩‍🏭*/ Woman_Factory_Worker("\uD83D\uDC69\u200D\uD83C\uDFED"),
    /**👨‍💼*/ Man_Office_Worker("\uD83D\uDC68\u200D\uD83D\uDCBC"),
    /**👩‍💼*/ Woman_Office_Worker("\uD83D\uDC69\u200D\uD83D\uDCBC"),
    /**👨‍🔬*/ Man_Scientist("\uD83D\uDC68\u200D\uD83D\uDD2C"),
    /**👩‍🔬*/ Woman_Scientist("\uD83D\uDC69\u200D\uD83D\uDD2C"),
    /**👨‍💻*/ Man_Technologist("\uD83D\uDC68\u200D\uD83D\uDCBB"),
    /**👩‍💻*/ Woman_Technologist("\uD83D\uDC69\u200D\uD83D\uDCBB"),
    /**👨‍🎤*/ Man_Singer("\uD83D\uDC68\u200D\uD83C\uDFA4"),
    /**👩‍🎤*/ Woman_Singer("\uD83D\uDC69\u200D\uD83C\uDFA4"),
    /**👨‍🎨*/ Man_Artist("\uD83D\uDC68\u200D\uD83C\uDFA8"),
    /**👩‍🎨*/ Woman_Artist("\uD83D\uDC69\u200D\uD83C\uDFA8"),
    /**👨‍✈️*/ Man_Pilot("\uD83D\uDC68\u200D✈️"),
    /**👩‍✈️*/ Woman_Pilot("\uD83D\uDC69\u200D✈️"),
    /**👨‍🚀*/ Man_Astronaut("\u200D\uD83D\uDE80"),
    /**👩‍🚀*/ Woman_Astronaut("\uD83D\uDC69\u200D\uD83D\uDE80"),
    /**👨‍🚒*/ Man_Firefighter("\uD83D\uDC68\u200D\uD83D\uDE92"),
    /**👩‍🚒*/ Woman_Firefighter("\uD83D\uDC69\u200D\uD83D\uDE92"),
    /**👮*/ Police_Officer("\uD83D\uDC6E"),
    /**👮‍♂️*/ Man_Police_Officer("\uD83D\uDC6E\u200D♂️"),
    /**👮‍♀️*/ Woman_Police_Officer("\u200D♀️"),
    /**🕵*/ Detective("\uD83D\uDD75"),
    /**🕵️‍♂️*/ Man_Detective("\uD83D\uDD75️\u200D♂️"),
    /**🕵️‍♀️*/ Woman_Detective("\uD83D\uDD75️\u200D♀️"),
    /**💂*/ Guard("\uD83D\uDC82"),
    /**💂‍♂️*/ Man_Guard("\u200D♂️"),
    /**💂‍♀️*/ Woman_Guard("\u200D♀️"),
    /**👷*/ Construction_Worker("\uD83D\uDC77"),
    /**👷‍♂️*/ Man_Construction_Worker("\u200D♂️"),
    /**👷‍♀️*/ Woman_Construction_Worker("\uD83D\uDC77\u200D♀️"),
    /**🤴*/ Prince("\uD83E\uDD34"),
    /**👸*/ Princess("\uD83D\uDC78"),
    /**👳*/ Person_Wearing_Turban("\uD83D\uDC73"),
    /**👳‍♂️*/ Man_Wearing_Turban("\uD83D\uDC73\u200D♂️"),
    /**👳‍♀️*/ Woman_Wearing_Turban("\u200D♀️"),
    /**👲*/ Man_With_Chinese_Cap("\uD83D\uDC72"),
    /**🧕*/ Woman_With_Headscarf("\uD83E\uDDD5"),
    /**🧔*/ Bearded_Person("\uD83E\uDDD4"),
    /**👱*/ Blond_Haired_Person("\uD83D\uDC71"),
    /**👱‍♂️*/ Blond_Haired_Man("\u200D♂️"),
    /**👱‍♀️*/ Blond_Haired_Woman("\u200D♀️"),
    /**🤵*/ Man_in_Tuxedo("\uD83E\uDD35"),
    /**👰*/ Bride_With_Veil("\uD83D\uDC70"),
    /**🤰*/ Pregnant_Woman("\uD83E\uDD30"),
    /**🤱*/ Breast_Feeding("\uD83E\uDD31"),
    /**👼*/ Baby_Angel("\uD83D\uDC7C"),
    /**🎅*/ Santa_Claus("\uD83C\uDF85"),
    /**🤶*/ Mrs_Claus("\uD83E\uDD36"),
    /**🧙‍♀️*/ Woman_Mage("\uD83E\uDDD9\u200D♀️"),
    /**🧙‍♂️*/ Man_Mage("\uD83E\uDDD9\u200D♂️"),
    /**🧚‍♀️*/ Woman_Fairy("\uD83E\uDDDA\u200D♀️"),
    /**🧚‍♂️*/ Man_Fairy("\uD83E\uDDDA\u200D♂️"),
    /**🧛‍♀️*/ Woman_Vampire("\uD83E\uDDDB\u200D♀️"),
    /**🧛‍♂️*/ Man_Vampire("\uD83E\uDDDB\u200D♂️"),
    /**🧜‍♀️*/ Mermaid("\uD83E\uDDDC\u200D♀️"),
    /**🧜‍♂️*/ Merman("\uD83E\uDDDC\u200D♂️"),
    /**🧝‍♀️*/ Woman_Elf("\uD83E\uDDDD\u200D♀️"),
    /**🧝‍♂️*/ Man_Elf("\uD83E\uDDDD\u200D♂️"),
    /**🧞‍♀️*/ Woman_Genie("\uD83E\uDDDE\u200D♀️"),
    /**🧞‍♂️*/ Man_Genie("\uD83E\uDDDE\u200D♂️"),
    /**🧟‍♀️*/ Woman_Zombie("\uD83E\uDDDF\u200D♀️"),
    /**🧟‍♂️*/ Man_Zombie("\uD83E\uDDDF\u200D♂️"),
    /**🙍*/ Person_Frowning("\uD83D\uDE4D"),
    /**🙍‍♂️*/ Man_Frowning("\u200D♂️"),
    /**🙍‍♀️*/ Woman_Frowning("\uD83D\uDE4D\u200D♀️"),
    /**🙎*/ Person_Pouting("\uD83D\uDE4E"),
    /**🙎‍♂️*/ Man_Pouting("\uD83D\uDE4E\u200D♂️"),
    /**🙎‍♀️*/ Woman_Pouting("\uD83D\uDE4E\u200D♀️"),
    /**🙅*/ Person_Gesturing_No("\uD83D\uDE45"),
    /**🙅‍♂️*/ Man_Gesturing_No("\uD83D\uDE45\u200D♂️"),
    /**🙅‍♀️*/ Woman_Gesturing_No("\uD83D\uDE45\u200D♀️"),
    /**🙆*/ Person_Gesturing_OK("\uD83D\uDE46"),
    /**🙆‍♂️*/ Man_Gesturing_OK("\uD83D\uDE46\u200D♂️"),
    /**🙆‍♀️*/ Woman_Gesturing_OK("\uD83D\uDE46\u200D♀️"),
    /**💁 */Person_Tipping_Hand("\uD83D\uDC81 "),
    /**💁‍♂️*/ Man_Tipping_Hand("\uD83D\uDC81\u200D♂️"),
    /**💁‍♀️*/ Woman_Tipping_Hand("\uD83D\uDC81\u200D♀️"),
    /**🙋*/ Person_Raising_Hand("\uD83D\uDE4B"),
    /**🙋‍♂️*/ Man_Raising_Hand("\uD83D\uDE4B\u200D♂️"),
    /**🙋‍♀️*/ Woman_Raising_Hand("\uD83D\uDE4B\u200D♀️"),
    /**🙇*/ Person_Bowing("\uD83D\uDE47"),
    /**🙇‍♂️*/ Man_Bowing("\uD83D\uDE47\u200D♂️"),
    /**🙇‍♀️*/ Woman_Bowing("\uD83D\uDE47\u200D♀️"),
    /**🤦*/ Person_Facepalming("\uD83E\uDD26"),
    /**🤦‍♂️*/ Man_Facepalming("\uD83E\uDD26\u200D♂️"),
    /**🤦‍♀️*/ Woman_Facepalming("\uD83E\uDD26\u200D♀️"),
    /**🤷*/ Person_Shrugging("\uD83E\uDD37"),
    /**🤷‍♂️*/ Man_Shrugging("\uD83E\uDD37\u200D♂️"),
    /**🤷‍♀️*/ Woman_Shrugging("\uD83E\uDD37\u200D♀️"),
    /**💆*/ Person_Getting_Massage("\uD83D\uDC86"),
    /**💆‍♂️*/ Man_Getting_Massage("\uD83D\uDC86\u200D♂️"),
    /**💆‍♀️*/ Woman_Getting_Massage("\uD83D\uDC86\u200D♀️"),
    /**💇*/ Person_Getting_Haircut("\uD83D\uDC87"),
    /**💇‍♂️*/ Man_Getting_Haircut("\uD83D\uDC87\u200D♂️"),
    /**💇‍♀️*/ Woman_Getting_Haircut("\uD83D\uDC87\u200D"),
    /**🚶*/ Person_Walking("\uD83D\uDEB6"),
    /**🚶‍♂️*/ Man_Walking("\uD83D\uDEB6\u200D♂️"),
    /**🚶‍♀️*/ Woman_Walking("\uD83D\uDEB6\u200D♀️"),
    /**🏃*/ Person_Running("\uD83C\uDFC3"),
    /**🏃‍♂️*/ Man_Running("\uD83C\uDFC3\u200D♂️"),
    /**🏃‍♀️*/ Woman_Running("\uD83C\uDFC3\u200D♀️"),
    /**💃*/ Woman_Dancing("\uD83D\uDC83"),
    /**🕺*/ Man_Dancing("\uD83D\uDD7A"),
    /**👯*/ People_With_Bunny_Ears("\uD83D\uDC6F"),
    /**👯‍♂️*/ Men_With_Bunny_Ears("\uD83D\uDC6F\u200D♂️"),
    /**👯‍♀️*/ Women_With_Bunny_Ears("\uD83D\uDC6F\u200D♀️"),
    /**🧖‍♀️*/ Woman_in_Steamy_Room("\uD83E\uDDD6\u200D♀️"),
    /**🧖‍♂️*/ Man_in_Steamy_Room("\uD83E\uDDD6\u200D♂️"),
    /**🕴*/ Man_in_Suit_Levitating("\uD83D\uDD74"),
    /**🗣*/ Speaking_Head("\uD83D\uDDE3"),
    /**👤*/ Bust_in_Silhouette("\uD83D\uDC64"),
    /**👥*/ Busts_in_Silhouette("\uD83D\uDC65"),
    /**👫*/Man_and_Woman_Holding_Hands("\uD83D\uDC6B"),
    /**👬*/ Two_Men_Holding_Hands("\uD83D\uDC6C"),
    /**👭*/ Two_Women_Holding_Hands("\uD83D\uDC6D"),
    /**💏*/ Kiss("\uD83D\uDC8F"),
    /**👨‍❤️‍💋‍👨*/ Kiss_Man_Man("\uD83D\uDC68\u200D❤️\u200D\uD83D\uDC8B\u200D\uD83D\uDC68"),
    /**👩‍❤️‍💋‍👩*/ Kiss_Woman_Woman("\uD83D\uDC69\u200D❤️\u200D\uD83D\uDC8B\u200D\uD83D\uDC69"),
    /**💑*/ Couple_With_Heart("\uD83D\uDC91"),
    /**👨‍❤️‍👨*/ Couple_With_Heart_Man_Man("\u200D❤️\u200D\uD83D\uDC68"),
    /**👩‍❤️‍👩*/ Couple_With_Heart_Woman_Woman("\u200D❤️\u200D\uD83D\uDC69"),
    /**👪*/ Family("\uD83D\uDC6A"),
    /**👨‍👩‍👦*/ Family_Man_Woman_Boy("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC66"),
    /**👨‍👩‍👧*/ Family_Man_Woman_Girl("\u200D\uD83D\uDC69\u200D\uD83D\uDC67"),
    /**👨‍👩‍👧‍👦*/ Family_Man_Woman_Girl_Boy("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66"),
    /**👨‍👩‍👦‍👦*/ Family_Man_Woman_Boy_Boy("\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC66\u200D\uD83D\uDC66"),
    /**👨‍👩‍👧‍👧*/ Family_Man_Woman_Girl_Girl("\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC67"),
    /**👨‍👨‍👦*/ Family_Man_Man_Boy("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC66"),
    /**👨👨‍👧*/ Family_Man_Man_Girl("\uD83D\uDC68\uD83D\uDC68\u200D\uD83D\uDC67"),
    /**👨‍👨‍👧‍👦*/ Family_Man_Man_Girl_Boy("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC66"),
    /**👨‍👨‍👦‍👦*/ Family_Man_Man_Boy_Boy("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC66\u200D\uD83D\uDC66"),
    /**👨‍👨‍👧‍👧*/ Family_Man_Man_Girl_Girl("\uD83D\uDC68\u200D\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC67"),
    /**👩‍👩‍👦*/ Family_Woman_Woman_Boy("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC66"),
    /**👩‍👩‍👧*/ Family_Woman_Woman_Girl("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC67"),
    /**👩‍👩‍👧‍👦*/ Family_Woman_Woman_Girl_Boy("\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66"),
    /**👩‍👩‍👦‍👦*/ Family_Woman_Woman_Boy_Boy("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC66\u200D\uD83D\uDC66"),
    /**👩‍👩‍👧‍👧*/ Family_Woman_Woman_Girl_Girl("\uD83D\uDC69\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC67"),
    /**👨‍👦*/ Family_Man_Boy("\uD83D\uDC68\u200D\uD83D\uDC66"),
    /**👨‍👦‍👦*/ Family_Man_Boy_Boy("\uD83D\uDC68\u200D\uD83D\uDC66\u200D\uD83D\uDC66"),
    /**👨‍👧*/ Family_Man_Girl("\uD83D\uDC68\u200D\uD83D\uDC67"),
    /**👨‍👧‍👦*/ Family_Man_Girl_Boy("\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC66"),
    /**👨‍👧‍👧*/ Family_Man_Girl_Girl("\uD83D\uDC68\u200D\uD83D\uDC67\u200D\uD83D\uDC67"),
    /**👩‍👦*/ Family_Woman_Boy("\uD83D\uDC69\u200D\uD83D\uDC66"),
    /**👩‍👦‍👦*/ Family_Woman_Boy_Boy("\uD83D\uDC69\u200D\uD83D\uDC66\u200D\uD83D\uDC66"),
    /**👩‍👧*/ Family_Woman_Girl("\uD83D\uDC69\u200D\uD83D\uDC67"),
    /**👩‍👧‍👦*/ Family_Woman_Girl_Boy("\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66"),
    /**👩‍👧‍👧*/ Family_Woman_Girl_Girl("\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC67"),
    /**🤳*/ Selfie("\uD83E\uDD33"),
    /**💪*/ Flexed_Biceps("\uD83D\uDCAA"),
    /**👈*/ Backhand_Index_Pointing_Left("\uD83D\uDC48"),
    /**👉*/ Backhand_Index_Pointing_Right("\uD83D\uDC49"),
    /**☝*/ Index_Pointing_Up("☝"),
    /**👆*/ Backhand_Index_Pointing_Up("\uD83D\uDC46"),
    /**🖕*/ Middle_Finger("\uD83D\uDD95"),
    /**👇*/ Backhand_Index_Pointing_Down("\uD83D\uDC47"),
    /**✌*/ Victory_Hand("✌"),
    /**🤞*/ Crossed_Fingers("\uD83E\uDD1E"),
    /**🖖*/ Vulcan_Salute("\uD83D\uDD96"),
    /**🤘*/ Sign_of_the_Horns("\uD83E\uDD18"),
    /**🖐*/ Hand_With_Fingers_Splayed("\uD83D\uDD90"),
    /**✋*/ Raised_Hand("✋"),
    /**👌*/ OK_Hand("\uD83D\uDC4C"),
    /**👍*/ Thumbs_Up("\uD83D\uDC4D"),
    /**👎*/ Thumbs_Down("\uD83D\uDC4E"),
    /**✊*/ Raised_Fist("✊"),
    /**👊*/ Oncoming_Fist("\uD83D\uDC4A"),
    /**🤛*/ Left_Facing_Fist("\uD83E\uDD1B"),
    /**🤜 */Right_Facing_Fist("\uD83E\uDD1C"),
    /**🤚*/ Raised_Back_of_Hand("\uD83E\uDD1A"),
    /**👋*/ Waving_Hand("\uD83D\uDC4B"),
    /**🤟*/ Love_You_Gesture("\uD83E\uDD1F"),
    /**✍*/ Writing_Hand("✍"),
    /**👏*/ Clapping_Hands("\uD83D\uDC4F"),
    /**👐*/ Open_Hands("\uD83D\uDC50"),
    /**🙌*/ Raising_Hands("\uD83D\uDE4C"),
    /**🤲*/ Palms_Up_Together("\uD83E\uDD32"),
    /**🙏*/ Folded_Hands("\uD83D\uDE4F"),
    /**🤝*/ Handshake("\uD83E\uDD1D"),
    /**💅*/ Nail_Polish("\uD83D\uDC85"),
    /**👂*/ Ear("\uD83D\uDC42"),
    /**👃*/ Nose("\uD83D\uDC43"),
    /**👣*/ Footprints("\uD83D\uDC63"),
    /**👀*/ Eyes("\uD83D\uDC40"),
    /**👁*/ Eye("\uD83D\uDC41"),
    /**🧠*/ Brain("\uD83E\uDDE0"),
    /**👅*/ Tongue("\uD83D\uDC45"),
    /**👄*/ Mouth("\uD83D\uDC44"),
    /**💋*/ Kiss_Mark("\uD83D\uDC8B"),
    /**👓*/ Glasses("\uD83D\uDC53"),
    /**🕶*/ Sunglasses("\uD83D\uDD76"),
    /**👔*/ Necktie("\uD83D\uDC54"),
    /**👕*/ T_Shirt("v"),
    /**👖*/ Jeans("\uD83D\uDC56"),
    /**🧣*/ Scarf("\uD83E\uDDE3"),
    /**🧤*/ Gloves("\uD83E\uDDE4"),
    /**🧥*/ Coat("\uD83E\uDDE5"),
    /**🧦*/ Socks("\uD83E\uDDE6"),
    /**👗*/ Dress("\uD83D\uDC57"),
    /**👘*/ Kimono("\uD83D\uDC58"),
    /**👙*/ Bikini("\uD83D\uDC59"),
    /**👚*/ Woman_Clothes("\uD83D\uDC5A"),
    /**👛*/ Purse("\uD83D\uDC5B"),
    /**👜*/ Handbag("\uD83D\uDC5C"),
    /**👝*/ Clutch_Bag("\uD83D\uDC5D"),
    /**🎒*/ School_Backpack("\uD83C\uDF92"),
    /**👞*/ Man_Shoe("\uD83D\uDC5E"),
    /**👟*/ Running_Shoe("\uD83D\uDC5F"),
    /**👠*/ High_Heeled_Shoe("\uD83D\uDC60"),
    /**👡*/ Woman_Sandal("\uD83D\uDC61"),
    /**👢*/ Woman_Boot("\uD83D\uDC62"),
    /**👑*/ Crown("v"),
    /**👒*/ Woman_Hat("\uD83D\uDC52"),
    /**🎩*/ Top_Hat("\uD83C\uDFA9"),
    /**🎓*/ Graduation_Cap("\uD83C\uDF93"),
    /**🧢*/ Billed_Cap("\uD83E\uDDE2"),
    /**⛑*/ Rescue_Worker_Helmet("⛑"),
    /**💄*/ Lipstick("\uD83D\uDC84"),
    /**💍*/ Ring("\uD83D\uDC8D"),
    /**🌂*/ Closed_Umbrella("\uD83C\uDF02"),
    /**☂*/ Umbrella("☂"),
    /**💼*/ Briefcase("\uD83D\uDCBC"),

    /** Животные и природа */



    /** Еда и напитки */

    /** Активности */

    /** Путешествия и места */

    /** Объекты */
    /** ⌨️ */ Keyboard("⌨️"),
    /** 🗺 */ World_Map("\uD83D\uDDFA"),
    /** ⌚ */ Watch("⌚"),
    /** 📕 */ Closed_Book("\uD83D\uDCD5"),
    /** 📖 */ Open_Book("\uD83D\uDCD6"),
    /** 📗 */ Green_Book("\uD83D\uDCD7"),
    /** 📘 */ Blue_Book("\uD83D\uDCD8"),
    /** 📙 */ Orange_Book("\uD83D\uDCD9"),
    /** 📃 */ Page_With_Curl("\uD83D\uDCC3"),
    /** ✏ */ Pencil("✏"),
    /** ✒ */ Black_Nib("✒"),
    /** 🖋 */ Fountain_Pen("\uD83D\uDD8B"),
    /** 🖊 */ Pen("\uD83D\uDD8A"),
    /** 🖌 */ Paintbrush("\uD83D\uDD8C"),
    /** 🖍 */ Crayon("\uD83D\uDD8D"),
    /** 🛠 */ Hammer_And_Wrench("\uD83D\uDEE0"),
    /** 🔧 */ Wrench("\uD83D\uDD27"),
    /** ⚙ */ Gear("⚙"),
    /** 📜 */ Scroll("\uD83D\uDCDC"),
    /** 📨 */ Incoming_Envelope("\uD83D\uDCE8"),
    /** 📇 */ Card_Index("\uD83D\uDCC7"),
    /** 📎 */ Paperclip("\uD83D\uDCCE"),
    /** 📝 */ Memo("\uD83D\uDCDD"),

    /** Символы */
    /** 🕛 */ Twelve_O_clock("\uD83D\uDD5B"),
    /** 🕧 */ Twelve_Thirty("\uD83D\uDD67"),
    /** 🕐 */ One_O_clock("\uD83D\uDD50"),
    /** 🕜 */ One_Thirty("\uD83D\uDD5C"),
    /** 🕑 */ Two_O_clock("\uD83D\uDD51"),
    /** 🕝 */ Two_Thirty("\uD83D\uDD5D"),
    /** 🕒 */ Three_O_clock("\uD83D\uDD52"),
    /** 🕞 */ Three_Thirty("\uD83D\uDD5E"),
    /** 🕓 */ Four_O_clock("\uD83D\uDD53"),
    /** 🕟 */ Four_Thirty("\uD83D\uDD5F"),
    /** 🕔 */ Five_O_clock("\uD83D\uDD54"),
    /** 🕠 */ Five_Thirty("\uD83D\uDD60"),
    /** 🕕 */ Six_O_clock("\uD83D\uDD55"),
    /** 🕡 */ Six_Thirty("\uD83D\uDD61"),
    /** 🕖 */ Seven_O_clock("\uD83D\uDD56"),
    /** 🕢 */ Seven_Thirty("\uD83D\uDD62"),
    /** 🕗 */ Eight_O_clock("\uD83D\uDD57"),
    /** 🕣 */ Eight_Thirty("\uD83D\uDD63"),
    /** 🕘 */ Nine_O_clock("\uD83D\uDD58"),
    /** 🕤 */ Nine_Thirty("\uD83D\uDD64"),
    /** 🕙 */ Ten_O_clock("\uD83D\uDD59"),
    /** 🕥 */ Ten_Thirty("\uD83D\uDD65"),
    /** 🕚 */ Eleven_O_clock("\uD83D\uDD5A"),
    /** 🕦 */ Eleven_Thirty("\uD83D\uDD66"),
    /** ⬅ */ Left_Arrow("⬅"),
    /** 🔙 */ Back_Arrow("\uD83D\uDD19"),
    /** ▶ */ Play_Button("▶"),
    /** ◀ */ Reverse_Button("◀"),
    /** ✅ */ White_Heavy_Check_Mark("✅"),
    /** ☑ */  Ballot_Box_With_Check("☑"),
    /** ✔ */ Heavy_Check_Mark("✔"),
    /** ✖ */ Heavy_Multiplication_X("✖"),
    /** ❌ */ Cross_Mark("❌"),
    /** ❎ */ Cross_Mark_Button("❎"),
    /** ➕ */ Heavy_Plus_Sign("➕"),
    /** ➖ */ Heavy_Minus_Sign("➖"),
    /** ‼ */ Double_Exclamation_Mark("‼"),
    /** ⁉ */ Exclamation_Question_Mark("⁉"),
    /** ❓ */ Question_Mark("❓"),
    /** ❔ */ White_Question_Mark("❔"),
    /** ❕ */ White_Exclamation_Mark("❕"),
    /** ❗ */ Exclamation_Mark("❗"),
    /** 🔵 */ BlueCircle("\uD83D\uDD35");

    String emoji;

    Emoji(String emoji)
    {
        this.emoji = emoji;
    }

    @Override
    public String toString()
    {
        String sb = "";
        sb = sb + this.emoji;
        return sb;
    }
}